name: Discord Voice Channel Monitor

on:
  #schedule:
    # Runs every 5 minutes
    #- cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  monitor-voice-channels:
    runs-on: ubuntu-latest
    
    steps:
    - name: Call Discord Voice API and save to Supabase
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        GUILD_ID: ${{ secrets.GUILD_ID }}
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      run: |
        # Call the live Netlify API endpoint
        curl -X POST "${{ secrets.NETLIFY_DEPLOY_URL }}/api/discord/voice-attendees/save" \
          -H "Content-Type: application/json" \
          --fail-with-body
        echo "Voice attendance data saved to Supabase via live API" 