name: Sync Project Data to Sheets

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:        # Allows manual triggering
    inputs:
      project_ids:
        description: 'Comma-separated list of project IDs to sync'
        required: false
        default: '1000107,1100271,1100022,1200148,1200147,1200220,1200202,1200254,1200201,1300135,1300134,1300130,1300050,1300036'  # Add your default project IDs here

jobs:
  sync-projects:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL2: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL2 }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY2: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY2 }}
      NEXT_PUBLIC_GOOGLE_SCRIPT_URL: ${{ secrets.NEXT_PUBLIC_GOOGLE_SCRIPT_URL }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run sync script
        run: node scripts/sync-projects.js
        env:
          PROJECT_IDS: ${{ github.event.inputs.project_ids || '1000107,1000108,1000109' }}